### PR TITLE
Adds new GR Plugin stands for FNLU and FQMA

### PR DESCRIPTION
**Pull request by SkyyStorm**
Issue #42, #45
- Added FNAN and FQBE GRPluginStands and settings files (empty)
- Added Stand information for FNLU
- Added Stand information for FQMA

Other
- Refactored the FASA plugin stands file

### CODE REVIEW

**Comment by SkyyStorm** [comment]
@vCaptainMike Should I complete this or wait for you to approve?

**Comment by vCaptainMike** [comment]
We can keep adding issues to the PR and review it next week with all the updates. I'll then review just to make sure we're good and that's it.

**Comment by vCaptainMike** [comment]
Perfect. Joshua is also working on Ground Layouts (doing the KMZs) on another repo, so that we can have a steady pipeline.

I've got the traffic analysis almost complete, so that should give us (at least) the two top airports per sector. Which would be awesome :)

**Review by vCaptainMike — APPROVED** [review]
All good.

**Comment by vCaptainMike** [comment]
Merged the Pending Updates to get a full review on all Sector Files as is. Everything looking good.

**Pull request merged**
